services:
  app:
    build: .
    ports:
      - "8181:80"
    environment:
      - readRulesFrom__fileConfig=/config/rules.yaml
    volumes:
      - type: bind
        source: ./tests/config/rules.yaml
        target: /config/rules.yaml
