apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redirector
resources:
  - ./namespace.yaml
  - ./deployment.yaml
  - ./service.yaml

configMapGenerator:
  - name: rules-config
    files:
      - ./rules.yaml
