apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app.kubernetes.io/name: redirector
spec:
  selector:
    app.kubernetes.io/name: redirector
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
